config:
  credentials_id: mbp-account-self
  # retry_with_prompt: true
  # retry_and_return: true
  # retry_count: 3

remote_groups:
  r_group:
    - name: wuxiaoran
      host: 172.16.10.52
  #   - name: node02
  #     host: node02.abc.net
  # r_group_2:
  #   - name: node03
  #     host: node03.abc.net

command_groups:
  c_group:
    - commands:
        - 'ls -lrt'
        - 'whoami'
    # - scripts:
    #     - 'test.sh'
  # c_group_2:
  #   - gets:
  #       - from: 'test.sh'
  #         into: 'test_new.sh'
  #         override: true
  #   - puts:
  #       - from: 'test.sh'
  #         into: '.'
  #   - removes:
  #       - 'test.sh'
  c_group:
    - commands:
        - 'pwd'
        - 'uname -a'

steps:
  deploy:
    - remote_groups:
        - r_group
      command_groups:
        - c_group
    # - remote_groups:
    #     - r_group_2
    #   command_groups:
    #     - c_group_2