config:
  credentials_id: mbp-account-self
  # retry_with_prompt: true
  # retry_and_return: true
  # retry_count: 3

remote_groups:
  r_group_1:
    - name: wuxiaoran
      host: 172.16.10.52
  #   - name: node02
  #     host: node02.abc.net
  # r_group_2:
  #   - name: node03
  #     host: node03.abc.net

command_groups:
  prebuild:
  #   - gets:
  #     - from: 'test.sh'
  #       into: 'test_new.sh'
  #       override: true
  #   - puts:
  #       - from: 'test.sh'
  #         into: '.'
  #   - removes:
  #       - 'test.sh'
    - commands:
        - 'ls -lrt'
        - 'whoami'
    # - scripts:
    #     - 'test.sh'
  # c_group_2:
  #   - gets:
  #       - from: 'test.sh'
  #         into: 'test_new.sh'
  #         override: true
  #   - puts:
  #       - from: 'test.sh'
  #         into: '.'
  #   - removes:
  #       - 'test.sh'
  predeploy:
    # - gets:
    #   - from: 'pre_build.sh'
    #     into: 'pre_build.sh'
    #     override: true
    - puts:
        - from: 'pre_build.sh'
          into: '.'
    - commands:
        - "bash pre_build.sh DOCKER_JRE_IMAGE=asd DOCKER_REGISTRY_IMAGE_TARGET=192.168 WORKSPACE=/abc/cde DOCKER_REGISTRY_URL=http:// ALIYUN_DOCKER_REGISTRY_LOGIN_PSW=asd"
    # - scripts:
    #     - "pre_build.sh DOCKER_JRE_IMAGE=asd DOCKER_REGISTRY_IMAGE_TARGET=192.168 WORKSPACE=/abc/cde DOCKER_REGISTRY_URL=http:// ALIYUN_DOCKER_REGISTRY_LOGIN_PSW=asd"
    # - removes:
    #     - 'test.sh'

steps:
  deploy:
    - remote_groups:
        - r_group_1
      command_groups:
        - prebuild
        - predeploy
    # - remote_groups:
    #     - r_group_2
    #   command_groups:
    #     - c_group_2